"""一键 Nuitka + PyInstaller 打包脚本（先编译，再封装）

目标
- 先用 Nuitka 把你的 Camera.py 编译成 CPython 扩展模块（.pyd/.so），避免把源码 .py 打进包里
- 再用 PyInstaller 负责“分发封装”（图标、依赖、海康 DLL 等）

说明（非常关键）
- 扩展模块的“模块名”和“文件名”必须一致，不能随意改名；因此这里会临时复制 Camera.py 为 camera_core.py 来编译。
- PyInstaller 无法从已编译的扩展模块里自动分析 import 依赖，所以需要显式写 hidden-import / collect-all。
"""

import os
import shutil
import subprocess
import sys
from importlib.machinery import EXTENSION_SUFFIXES
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

# ---------- 你的项目文件 ----------
CAMERA_SRC = PROJECT_ROOT / "Camera.py"
ICON_FILE = PROJECT_ROOT / "Camera.ico"
WIN64_DIR = PROJECT_ROOT / "Win64_x64"

# ---------- Nuitka 输出 ----------
NUITKA_MODULE_NAME = "camera_core"  # 生成的扩展模块名
NUITKA_TEMP_PY = PROJECT_ROOT / f"{NUITKA_MODULE_NAME}.py"
NUITKA_OUT_DIR = PROJECT_ROOT / "build_nuitka"

# ---------- PyInstaller 输出 ----------
ENTRY_SCRIPT = PROJECT_ROOT / "Camera_entry.py"   # PyInstaller 入口
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"
SPEC_FILE = PROJECT_ROOT / "Camera.spec"
RTHOOK_ORT = PROJECT_ROOT / "rth_onnxruntime.py"
# 这些模块都在 Camera.py 里有 import（但 PyInstaller 现在看不到 Camera.py 了，所以要显式告诉它）
HIDDEN_IMPORTS = [
    # 业务依赖
    "onnxruntime",
    "onnxruntime.capi.onnxruntime_pybind11_state",
    "cv2",
    "numpy",

    # PyQt5（保证 hook 能触发，打包 Qt 插件）
    "PyQt5",
    "PyQt5.QtCore",
    "PyQt5.QtGui",
    "PyQt5.QtWidgets",

    # 海康 SDK 的 Python 包装（Camera.py 里 try-import 这些）
    "MvCameraControl_class",
    "CameraParams_const",
    "CameraParams_header",
    "MvErrorDefine_const",
    "PixelType_header",
]

# 复制 metadata（你原脚本里就有，继续保留；多加了 PyQt5 以防某些环境缺元数据）
METADATA_PACKAGES = [
    "onnxruntime",
    "opencv-python",
    "numpy",
    "PyQt5",
]


def _rm(path: Path) -> None:
    if path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path, ignore_errors=True)


def clean_previous_artifacts() -> None:
    """删除上一次构建的产物，确保干净输出。"""
    for p in (DIST_DIR, BUILD_DIR, SPEC_FILE, NUITKA_OUT_DIR):
        _rm(p)

    # 清理上一次生成的入口/临时文件
    for p in (ENTRY_SCRIPT, NUITKA_TEMP_PY, RTHOOK_ORT):
        if p.exists():
            p.unlink()

    # 清理根目录里可能残留的编译产物（camera_core*.pyd/.so 等）
    for item in PROJECT_ROOT.iterdir():
        if item.is_file() and item.name.startswith(NUITKA_MODULE_NAME) and any(
            item.name.endswith(suf) for suf in EXTENSION_SUFFIXES
        ):
            item.unlink()


def prepare_nuitka_source() -> None:
    """临时复制 Camera.py -> camera_core.py，让 Nuitka 用 camera_core 作为模块名编译。"""
    if not CAMERA_SRC.exists():
        raise FileNotFoundError(f"找不到 {CAMERA_SRC}")

    # 直接复制即可；Camera.py 只有在 __main__ 时才会 main()
    shutil.copy2(CAMERA_SRC, NUITKA_TEMP_PY)


def run_nuitka_compile() -> Path:
    """使用 Nuitka 把 camera_core.py 编译为扩展模块，并返回编译产物路径。"""
    NUITKA_OUT_DIR.mkdir(parents=True, exist_ok=True)


    cmd = [
        sys.executable,
        "-m",
        "nuitka",
        "--mode=module",
        "--msvc=latest",
        f"--output-dir={NUITKA_OUT_DIR}",
        "--no-pyi-file",               # 不生成 .pyi（可选）
        "--assume-yes-for-downloads",  # Nuitka 需要下载时自动同意（可选）
        str(NUITKA_TEMP_PY),
    ]

    subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

    # 在输出目录里找 camera_core 的扩展模块文件
    candidates = []
    for p in NUITKA_OUT_DIR.iterdir():
        if p.is_file() and p.name.startswith(NUITKA_MODULE_NAME) and any(
            p.name.endswith(suf) for suf in EXTENSION_SUFFIXES
        ):
            candidates.append(p)

    if not candidates:
        raise FileNotFoundError(
            f"未在 {NUITKA_OUT_DIR} 找到编译产物（{NUITKA_MODULE_NAME}*.pyd/.so）。"
        )

    # 若存在多个，按字典序取一个最可能的（通常是带 cp311-win_amd64 的那个）
    candidates.sort(key=lambda x: x.name)
    built_module = candidates[0]

    # 复制到项目根目录，确保 PyInstaller 能 import 到
    target = PROJECT_ROOT / built_module.name
    shutil.copy2(built_module, target)
    return target


def write_entry_script() -> None:
    """生成 PyInstaller 入口脚本：import 扩展模块并调用 main()."""
    content = """# Auto-generated by build script
import os, sys

base = getattr(sys, "_MEIPASS", os.path.dirname(__file__))

import camera_core

if __name__ == "__main__":
    camera_core.main()
"""
    ENTRY_SCRIPT.write_text(content, encoding="utf-8")



def write_runtime_hook_onnxruntime() -> None:
    """生成 PyInstaller runtime hook：修正 onnxruntime DLL 搜索路径，并输出诊断信息（Windows）。"""
    content = r"""# Auto-generated by build script (PyInstaller runtime hook)
import os
import sys
import traceback
import importlib.util
from pathlib import Path

base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))

def _p(msg: str) -> None:
    try:
        print(msg, file=sys.stderr, flush=True)
    except Exception:
        pass

# 兜底：OpenMP/MKL 冲突时允许重复加载（仅用于排障/兼容）
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

# onedir: base 往往是 dist\App\_internal
# onefile: base 是临时解压目录
candidates = [
    base,
    base / "onnxruntime",
    base / "onnxruntime" / "capi",
    base.parent,
    base.parent / "onnxruntime",
    base.parent / "onnxruntime" / "capi",
    base / "_internal",
    base / "_internal" / "onnxruntime",
    base / "_internal" / "onnxruntime" / "capi",
    base.parent / "_internal",
    base.parent / "_internal" / "onnxruntime",
    base.parent / "_internal" / "onnxruntime" / "capi",
]

added = []
for p in candidates:
    try:
        if isinstance(p, Path) and p.exists():
            try:
                os.add_dll_directory(str(p))
                added.append(str(p))
            except Exception:
                pass
            os.environ["PATH"] = str(p) + os.pathsep + os.environ.get("PATH", "")
    except Exception:
        pass

_p(f"[ORT-DIAG] base={base}")
_p("[ORT-DIAG] added dll dirs:")
for d in added:
    _p(f"  - {d}")

# 不触发 import，仅定位包路径
try:
    spec = importlib.util.find_spec("onnxruntime")
    _p(f"[ORT-DIAG] find_spec(onnxruntime)={spec}")
    if spec and spec.submodule_search_locations:
        pkg_dir = Path(list(spec.submodule_search_locations)[0])
        capi_dir = pkg_dir / "capi"
        _p(f"[ORT-DIAG] pkg_dir={pkg_dir}")
        _p(f"[ORT-DIAG] capi_dir={capi_dir} exists={capi_dir.exists()}")
        if capi_dir.exists():
            for f in sorted(capi_dir.iterdir(), key=lambda x: x.name.lower()):
                _p(f"    {f.name}")
except Exception:
    _p("[ORT-DIAG] spec probe failed:")
    _p(traceback.format_exc())

# 提前 import（如果这里失败，控制台会有完整 traceback）
try:
    import onnxruntime.capi.onnxruntime_pybind11_state  # noqa: F401
    _p("[ORT-DIAG] pre-import onnxruntime_pybind11_state OK")
except Exception:
    _p("[ORT-DIAG] pre-import onnxruntime_pybind11_state FAILED:")
    _p(traceback.format_exc())
"""
    RTHOOK_ORT.write_text(content, encoding="utf-8")

def run_pyinstaller() -> None:
    """调用 PyInstaller 进行打包。"""
    data_sep = ";" if os.name == "nt" else ":"

    # ---- onnxruntime capi binaries (force colocate pyd/dll) ----
    ort_capi_files = []
    try:
        import onnxruntime  # type: ignore
        ort_pkg_dir = Path(onnxruntime.__file__).resolve().parent
        ort_capi_dir = ort_pkg_dir / "capi"
        if ort_capi_dir.exists():
            ort_capi_files = [
                p for p in ort_capi_dir.iterdir()
                if p.is_file() and p.suffix.lower() in (".dll", ".pyd")
            ]
    except Exception as e:
        print(f"[PyI] WARN: failed to probe onnxruntime capi dir: {e}")
    add_data_arg = f"{ICON_FILE}{data_sep}."  # 将图标文件复制到 dist 根目录

    binaries = []

    # ---- 强制把 onnxruntime 的 capi 目录“整包”带进来（关键修复）
    # 你现在 dist 里只看到了 onnxruntime.dll / onnxruntime_providers_shared.dll，
    # 但 onnxruntime 还常依赖 mklml.dll / libiomp5md.dll / onnxruntime_providers_cpu.dll 等，
    # 这些文件名不一定以 "onnxruntime" 开头，所以光靠 --collect-all 可能漏收。
    ort_datas = []
    try:
        import onnxruntime  # noqa: F401
        ort_pkg_dir = Path(onnxruntime.__file__).resolve().parent
        ort_capi_dir = ort_pkg_dir / "capi"
        ort_dest_dir = r"onnxruntime\capi" if os.name == "nt" else "onnxruntime/capi"

        if ort_capi_dir.exists():
            for f in sorted(ort_capi_dir.iterdir()):
                if not f.is_file():
                    continue
                suf = f.suffix.lower()
                if suf in (".dll", ".pyd", ".so", ".dylib"):
                    binaries.extend(["--add-binary", f"{f}{data_sep}{ort_dest_dir}"])
                else:
                    ort_datas.extend(["--add-data", f"{f}{data_sep}{ort_dest_dir}"])
        else:
            print(f"[WARN] onnxruntime.capi not found at: {ort_capi_dir}")
    except Exception as e:
        print(f"[WARN] Failed to force-collect onnxruntime capi files: {e}")

    if WIN64_DIR.exists():
        for item in WIN64_DIR.iterdir():
            if item.is_file():
                binaries.extend(["--add-binary", f"{item}{data_sep}Win64_x64"])

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--noconsole",  # 显示控制台，便于排查 DLL/导入问题
        
        "--name",
        "Camera",
        "--icon",
        str(ICON_FILE),
        "--add-data",
        add_data_arg,
        "--runtime-hook",
        str(RTHOOK_ORT),

        # 关键：确保 Qt / OpenCV 等 hook 资源被完整收集
        "--collect-all",
        "PyQt5",
        "--collect-all",
        "cv2",
        "--collect-all",
        "onnxruntime",
    ]

    for hidden in HIDDEN_IMPORTS:
        cmd.extend(["--hidden-import", hidden])

    for meta_pkg in METADATA_PACKAGES:
        cmd.extend(["--copy-metadata", meta_pkg])

    cmd.extend([
        *ort_datas,
        *binaries,
        str(ENTRY_SCRIPT),
    ])

    subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

def remove_unwanted_files() -> None:
    """确保输出目录中不包含 config.json。"""
    if not DIST_DIR.exists():
        return

    for candidate in DIST_DIR.iterdir():
        if candidate.is_dir():
            cfg = candidate / "config.json"
            if cfg.exists():
                cfg.unlink()
        elif candidate.is_file() and candidate.name == "config.json":
            candidate.unlink()


def cleanup_temp_files() -> None:
    """构建完成后清理临时源码文件（可按需保留用于下次增量构建）。"""
    for p in (ENTRY_SCRIPT, NUITKA_TEMP_PY):
        if p.exists():
            p.unlink()


def main() -> None:
    clean_previous_artifacts()
    prepare_nuitka_source()

    built_ext = run_nuitka_compile()
    print(f"[OK] Nuitka built: {built_ext.name}")

    write_entry_script()
    write_runtime_hook_onnxruntime()
    run_pyinstaller()
    remove_unwanted_files()
    cleanup_temp_files()
    print("[OK] Done. Check dist/Camera/ ...")


if __name__ == "__main__":
    main()
